backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  # This line should *not* be indented
media_folder: "/static/image" # Media files will be stored in the repo under images/uploads
public_folder: "/image" 
display_url: https://darinjmb.com
logo_url: "/image/iconsforwebsite/32x32.png"
collections:
  - name: "video" # Used in routes, e.g., /admin/collections/blog
    label: "Video" # Used in the UI
    folder: "content/capturing/video" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image"}
      - { name: "video", label: "Video Embed Code", widget: "text", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["video"]}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Collage" # Used in routes, e.g., /admin/collections/blog
    label: "Collage" # Used in the UI
    folder: "content/creation/Collage" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["collage"]}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "content/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "profileimage", widget: "image" }
      - { label: "Content Category", name: "contentdesc", widget: "string" }
      - { label: "About Blurb", name: "body", widget: "markdown" }
  - name: "AI" # Used in routes, e.g., /admin/collections/blog
    label: "A.I" # Used in the UI
    folder: "content/creation/AI" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["ai"]}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Drawing" # Used in routes, e.g., /admin/collections/blog
    label: "Drawing" # Used in the UI
    folder: "content/creation/Drawing" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["drawing"]}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Graphic" # Used in routes, e.g., /admin/collections/blog
    label: "Graphic" # Used in the UI
    folder: "content/creation/Design_1" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["design_1"]}
      - { label: "Body", name: "body", widget: "markdown" }
     
  - name: "Logo" # Used in routes, e.g., /admin/collections/blog
    label: "Logo" # Used in the UI
    folder: "content/creation/Design_1" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image"}
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["design_1"]}
      - { label: "Body", name: "body", widget: "markdown" }
      
  - name: "Poster" # Used in routes, e.g., /admin/collections/blog
    label: "Poster" # Used in the UI
    folder: "content/creation/Design_1" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string",  required: false}
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["design_1"]}
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "bird" # Used in routes, e.g., /admin/collections/blog
    label: "bird" # Used in the UI
    folder: "content/capturing/bird" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["bird"]}
      - { label: "Body", name: "body", widget: "markdown" }
    
  - name: "editorial" # Used in routes, e.g., /admin/collections/blog
    label: "Editorial" # Used in the UI
    folder: "content/capturing/editorial" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["editorial"]}
      - { label: "Body", name: "body", widget: "markdown" }
    
  - name: "product" # Used in routes, e.g., /admin/collections/blog
    label: "Product" # Used in the UI
    folder: "content/capturing/product" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "featuredimage", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - { label: "Alt Text", name: "alt", widget: "string", required: false }
      - { label: "Post Type", name: "type", widget: "select", options: ["content", "other"]}
      - { label: "Content Description", name: "descblurb", widget: "string" }
      - { label: "Content Year", name: "postyear", widget: "string" }
      - { label: "Subcategory", name: "contentdesc", widget: "select", options: ["product"]}
      - { label: "Body", name: "body", widget: "markdown" }
     

    

